services:
#    vidarl_dummy.example:
#        class: Vidarl\DummyBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    vidarl_dummy.purge_client.dummyPurge:
        class: Vidarl\DummyBundle\PurgeClient\DummyPurgeClient

    vidarl_dummy.http_cache.user_context_provider.paid_subscriber:
        class: Vidarl\DummyBundle\ContextProvider\PaidSubscriber
        arguments: ["@ezpublish.api.repository"]
        tags:
            - { name: fos_http_cache.user_context_provider }

    vidarl_dummy.twig.filter.has_paid:
        class: Vidarl\DummyBundle\Twig\HasPaidExtension
        arguments: ["@ezpublish.api.repository"]
        tags:
            - { name: twig.extension}
